# Generated by Django 4.2 on 2023-05-01 19:00

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booleanfield", models.BooleanField(default=True)),
                ("charfield", models.CharField(default="Foo Bar Baz", max_length=250)),
                (
                    "emailfield",
                    models.EmailField(default="name@example.com", max_length=254),
                ),
                ("slugfield", models.SlugField(default="foo-bar-baz")),
                ("textfield", models.TextField(default="Foo\nBar\nBaz")),
                ("binaryfield", models.BinaryField(default=b"Foo Bar Baz")),
                ("urlfield", models.URLField(default="http://example.com")),
                (
                    "genericipaddressfield",
                    models.GenericIPAddressField(
                        default="2001:db8:3333:4444:5555:6666:7777:8888"
                    ),
                ),
                ("datefield", models.DateField(default=datetime.date(2010, 10, 10))),
                (
                    "datetimefield",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2010, 10, 10, 10, 10, 10, 10, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "durationfield",
                    models.DurationField(
                        default=datetime.timedelta(days=10, seconds=36610)
                    ),
                ),
                ("timefield", models.TimeField(default=datetime.time(10, 10, 10, 10))),
                ("filepathfield", models.FilePathField(default="/foo/bar/baz")),
                (
                    "decimalfield",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("12.0025"), max_digits=16
                    ),
                ),
                ("floatfield", models.FloatField(default=0.125)),
                ("integerfield", models.IntegerField(default=125)),
                ("bigintegerfield", models.BigIntegerField(default=5000000000000)),
                (
                    "positivebigintegerfield",
                    models.PositiveBigIntegerField(default=5000000000000),
                ),
                ("smallintegerfield", models.SmallIntegerField(default=25)),
                (
                    "positivesmallintegerfield",
                    models.PositiveSmallIntegerField(default=25),
                ),
                ("positiveintegerfield", models.PositiveIntegerField(default=25)),
                (
                    "uuidfield",
                    models.UUIDField(
                        default=uuid.UUID("6562d5ee-083c-4131-b878-9f0ec7dcbf5d")
                    ),
                ),
                (
                    "jsonfield",
                    models.JSONField(
                        default={"abc": [123, 456], "foo": {"bar": "baz"}, "xyz": True}
                    ),
                ),
                (
                    "filefield",
                    models.FileField(default="abc/xyz/foo.bar", upload_to=""),
                ),
                (
                    "json",
                    models.JSONField(
                        default={
                            "bigintegerfield": 5000000000000,
                            "booleanfield": True,
                            "charfield": "Foo Bar Baz",
                            "datefield": "2010-10-10",
                            "datetimefield": "2010-10-10 10:10:10.000010+00:00",
                            "decimalfield": "12.0025",
                            "durationfield": "10 days, 10:10:10",
                            "emailfield": "name@example.com",
                            "filefield": "abc/xyz/foo.bar",
                            "filepathfield": "/foo/bar/baz",
                            "floatfield": 0.125,
                            "genericipaddressfield": "2001:db8:3333:4444:5555:6666:7777:8888",
                            "integerfield": 125,
                            "jsonfield": {
                                "abc": [123, 456],
                                "foo": {"bar": "baz"},
                                "xyz": True,
                            },
                            "positivebigintegerfield": 5000000000000,
                            "positiveintegerfield": 25,
                            "positivesmallintegerfield": 25,
                            "slugfield": "foo-bar-baz",
                            "smallintegerfield": 25,
                            "textfield": "Foo\nBar\nBaz",
                            "timefield": "10:10:10.000010",
                            "urlfield": "http://example.com",
                            "uuidfield": "6562d5ee-083c-4131-b878-9f0ec7dcbf5d",
                        }
                    ),
                ),
                (
                    "foreignkey",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foreignkey_reverse",
                        to="app.testmodel",
                    ),
                ),
                (
                    "manytomanyfield",
                    models.ManyToManyField(
                        related_name="manytomanyfield_reverse", to="app.testmodel"
                    ),
                ),
                (
                    "onetoonefield",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onetoonefield_reverse",
                        to="app.testmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Implementation",
            },
        ),
    ]
