# Generated by Django 4.2 on 2023-05-04 04:09

import typing

import django.db.models.deletion
import tests.app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charfield", models.CharField(max_length=255, null=True)),
                (
                    "decimalfield",
                    models.DecimalField(decimal_places=6, max_digits=60, null=True),
                ),
                ("booleanfield", models.BooleanField(null=True)),
                ("emailfield", models.EmailField(max_length=254, null=True)),
                ("slugfield", models.SlugField(null=True)),
                ("textfield", models.TextField(null=True)),
                ("urlfield", models.URLField(null=True)),
                ("binaryfield", models.BinaryField(null=True)),
                ("genericipaddressfield", models.GenericIPAddressField(null=True)),
                ("datefield", models.DateField(null=True)),
                ("datetimefield", models.DateTimeField(null=True)),
                ("durationfield", models.DurationField(null=True)),
                ("timefield", models.TimeField(null=True)),
                ("filepathfield", models.FilePathField(null=True)),
                ("floatfield", models.FloatField(null=True)),
                ("integerfield", models.IntegerField(null=True)),
                ("bigintegerfield", models.BigIntegerField(null=True)),
                ("positivebigintegerfield", models.PositiveBigIntegerField(null=True)),
                ("smallintegerfield", models.SmallIntegerField(null=True)),
                (
                    "positivesmallintegerfield",
                    models.PositiveSmallIntegerField(null=True),
                ),
                ("positiveintegerfield", models.PositiveIntegerField(null=True)),
                ("uuidfield", models.UUIDField(null=True)),
                ("jsonfield", models.JSONField(null=True)),
                ("filefield", models.FileField(null=True, upload_to="")),
                (
                    "json",
                    models.JSONField(
                        default=dict, encoder=tests.app.models.JSONEncoder, null=True
                    ),
                ),
                (
                    "foreignkey",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="foreignkey_reverse",
                        to="app.testmodel",
                    ),
                ),
                (
                    "manytomanyfield",
                    models.ManyToManyField(
                        related_name="manytomanyfield_reverse", to="app.testmodel"
                    ),
                ),
                (
                    "onetoonefield",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onetoonefield_reverse",
                        to="app.testmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Implementation",
            },
            bases=(models.Model,),
        ),
    ]
