# Generated by Django 4.1.4 on 2022-12-27 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Vert Bad"),
                            (2, "Bad"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ],
                        null=True,
                    ),
                ),
                ("date_published", models.DateTimeField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="books",
                        to="example.author",
                    ),
                ),
            ],
        ),
    ]
