# Generated by Django 4.1.6 on 2023-02-10 02:03

import django.db.models.deletion
import example.aliases.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("CAIRO", "Cairo"),
                            ("LONDON", "London"),
                            ("NAIROBI", "Nairobi"),
                            ("NEW_YORK", "New York"),
                            ("TOKYO", "Tokyo"),
                        ],
                        default=example.aliases.models.City.random,
                        max_length=64,
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=example.aliases.models.rand_commission,
                        max_digits=4,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "author_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="aliases.author",
                    ),
                ),
                ("house", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
            bases=("aliases.author",),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=example.aliases.models.rand_price,
                        max_digits=12,
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Very Bad"),
                            (2, "Bad"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "num_sold",
                    models.IntegerField(default=example.aliases.models.rand_num_sold),
                ),
                (
                    "published_on",
                    models.DateTimeField(
                        default=example.aliases.models.rand_date, null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(default=example.aliases.models.Book.default_data),
                ),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="aliases.author"),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="books",
                        to="aliases.publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("aliases.book",),
        ),
        migrations.CreateModel(
            name="Magazine",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("aliases.publication",),
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("aliases.publication",),
        ),
    ]
