# Generated by Django 4.1.4 on 2022-12-30 20:40

from django.db import migrations, models
import django.db.models.deletion
import example.aliases.models
import functools
import random


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("CAIRO", "Cairo"),
                            ("LONDON", "London"),
                            ("NAIROBI", "Nairobi"),
                            ("NEW_YORK", "New York"),
                            ("TOKYO", "Tokyo"),
                        ],
                        default=example.aliases.models.City.random,
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=example.aliases.models.rand_price,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Vert Bad"),
                            (2, "Bad"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "num_sold",
                    models.IntegerField(
                        default=functools.partial(random.Random.randint, *(0, 10), **{})
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        default=example.aliases.models.rand_date, null=True
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="aliases.author"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="books",
                        to="aliases.publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
