# Generated by Django 4.1.6 on 2023-02-11 01:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.expressions
import example.aliases.models
import zana.django.models.aliases


class Migration(migrations.Migration):
    dependencies = [
        ("aliases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="income",
            field=zana.django.models.aliases.AliasField(
                expression=example.aliases.models.Author.get_income,
                internal=models.DecimalField(decimal_places=2, max_digits=20),
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="num_books",
            field=zana.django.models.aliases.AliasField(
                expression=django.db.models.aggregates.Count("books__pk"),
                internal=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="publishers",
            field=zana.django.models.aliases.AliasField(
                expression=example.aliases.models.Author.get_publishers_annotation,
                getter=example.aliases.models.Author.get_publishers,
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="rating",
            field=zana.django.models.aliases.AliasField(
                annotate=True,
                expression=django.db.models.aggregates.Avg("books__rating"),
                internal=models.DecimalField(
                    decimal_places=2, default=Decimal("0.00"), max_digits=20
                ),
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="version",
            field=zana.django.models.aliases.AliasField(expression="updated_at"),
        ),
        migrations.AddField(
            model_name="book",
            name="commission",
            field=zana.django.models.aliases.AliasField(
                cache=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("price"), "*", models.F("publisher__commission")
                ),
                getter=example.aliases.models.Book.get_commission,
                internal=models.DecimalField(decimal_places=2, max_digits=20),
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="commission_income",
            field=zana.django.models.aliases.AliasField(
                cache=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("commission"), "*", models.F("num_sold")
                ),
                getter=example.aliases.models.Book.get_commission_income,
                internal=models.DecimalField(decimal_places=2, max_digits=20),
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="gross_income",
            field=zana.django.models.aliases.AliasField(
                cache=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("price"), "*", models.F("num_sold")
                ),
                getter=example.aliases.models.Book.get_gross_income,
                internal=models.DecimalField(decimal_places=2, max_digits=20),
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="net_income",
            field=zana.django.models.aliases.AliasField(
                cache=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("net_price"), "*", models.F("num_sold")
                ),
                getter=example.aliases.models.Book.get_net_income,
                internal=models.DecimalField(decimal_places=2, max_digits=20),
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="net_price",
            field=zana.django.models.aliases.AliasField(
                cache=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("price"), "-", models.F("commission")
                ),
                getter=example.aliases.models.Book.get_net_price,
                internal=models.DecimalField(decimal_places=2, max_digits=20),
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="published_by",
            field=zana.django.models.aliases.AliasField(
                expression=models.F("publisher__name"),
                path="publisher.name",
                setter=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="version",
            field=zana.django.models.aliases.AliasField(expression="updated_at"),
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=zana.django.models.aliases.AliasField(
                defer=True,
                expression=models.F("published_on__year"),
                internal=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="income",
            field=zana.django.models.aliases.AliasField(
                expression=example.aliases.models.Publisher.get_income
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="num_books",
            field=zana.django.models.aliases.AliasField(
                expression=django.db.models.aggregates.Count("books__pk"),
                internal=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="rating",
            field=zana.django.models.aliases.AliasField(
                annotate=True,
                expression=django.db.models.aggregates.Avg("books__rating"),
                internal=models.DecimalField(
                    decimal_places=2, default=Decimal("0.00"), max_digits=20
                ),
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="version",
            field=zana.django.models.aliases.AliasField(expression="updated_at"),
        ),
    ]
