# Generated by Django 4.1.6 on 2023-02-06 04:59

import zana.django.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "aliases",
            "0002_author_created_at_author_updated_at_book_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Novel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("aliases.book",),
        ),
        migrations.AddField(
            model_name="author",
            name="version",
            field=zana.django.models.fields.AliasField(default=None),
        ),
        migrations.AddField(
            model_name="book",
            name="version",
            field=zana.django.models.fields.AliasField(default=None),
        ),
        migrations.AddField(
            model_name="publisher",
            name="version",
            field=zana.django.models.fields.AliasField(default=None),
        ),
    ]
