# Generated by Django 4.1.7 on 2023-02-15 20:24

import zana.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliases", "0003_book_tag_book_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="chapters",
            field=zana.django.models.AliasField(
                expression=models.F("data__content__chapters"),
                setter=True,
                source=[("ATTR", ("data",)), ("ITEM", ("content", "chapters"))],
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="date",
            field=zana.django.models.AliasField(
                defer=True,
                expression="published_on__date",
                source=[("ATTR", ("published_on", "date")), ("CALL",)],
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="num_pages",
            field=zana.django.models.AliasField(
                cast=True,
                deleter=True,
                expression=models.F("data__content__pages"),
                internal=models.IntegerField(),
                setter=True,
                source=[("ATTR", ("data",)), ("ITEM", ("content", "pages"))],
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="topics",
            field=zana.django.models.AliasField(
                expression=models.F("data__content__chapters__0__topics"),
                setter=True,
                source=[
                    ("ATTR", ("data",)),
                    ("ITEM", ("content", "chapters", 0, "topics")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_by",
            field=zana.django.models.AliasField(
                deleter=True,
                expression=models.F("publisher__name"),
                setter=True,
                source=[("ATTR", ("publisher", "name"))],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="tag",
            field=zana.django.models.AliasField(
                cast=True,
                deleter=True,
                expression=models.F("data__tags__0"),
                internal=models.TextField(),
                setter=True,
                source=[("ATTR", ("data",)), ("ITEM", ("tags", 0))],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=zana.django.models.AliasField(
                expression=models.F("published_on__year"),
                internal=models.IntegerField(),
                source=[("ATTR", ("published_on", "year"))],
            ),
        ),
    ]
