# Generated by Django 4.1.7 on 2023-02-15 22:43

from django.db import migrations
import zana.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("aliases", "0004_book_chapters_book_date_book_num_pages_book_topics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=zana.django.models.AliasField(
                expression="data__tags",
                setter=True,
                source=[
                    ("ATTR", ("data",)),
                    ("ITEM", ("tags",)),
                    ("SLICE", ((None, 2, None),)),
                ],
            ),
        ),
    ]
