# Generated by Django 4.1.7 on 2023-02-18 04:31

from django.db import migrations, models
import zana.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("aliases", "0006_book_desc_c_book_desc_r_book_desc_s_alter_book_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_short",
            field=zana.django.models.AliasField(
                expression=models.Case(
                    models.When(num_pages__lte=500, then=models.Value(True)),
                    default=models.Value(False),
                ),
                internal=models.BooleanField(),
                json=True,
            ),
        ),
    ]
