name: CI/CD

on:
  push:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        if: matrix.platform == 'ubuntu-latest'
        with:
            postgresql version: '12.14'
            postgresql user: 'root' 
            postgresql password: 'root' 
      - name: Set up MySQL
        if: matrix.platform == 'ubuntu-latest'
        run: sudo /etc/init.d/mysql start
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install tox tox-gh-actions
      - name: Test - run tox
        run: tox p -- --cov-append --cov-report xml
        env:
            PLATFORM: ${{ matrix.platform }}
            DATABASES: mysql=mysql://root:root@localhost/test_db;pgsql=postgres://root:root@localhost/test_db;sqlite=sqlite:////tmp/test-sqlite.db
      - name: Upload code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
            name: django-zana
            env_vars: OS,PYTHON
            fail_ci_if_error: true
            