name: CI/CD

on:
  push:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up MySQL
        run: |
            sudo /etc/init.d/mysql start
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install tox tox-gh-actions
      - name: Test
        run: tox
    #   - name: Export Coverage Report
    #     run: poetry run coverage xml
    #   - name: Upload code coverage
    #     uses: codecov/codecov-action@v2.1.0
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #       file: ./coverage.xml
    #       name: django-zana
    #       env_vars: OS,PYTHON
    #       fail_ci_if_error: true
  
          
          
          